### ISSUE TITLE
Required Parameter?

### ISSUE THREAD

**Issue by ghost** [k42b3/psx-sample#1]
Is it possible to tag a @Required("true") for your entity and display that boolean in the front end api documentation? If so, how would i go about in doing this?

I'm sorry that i have to open an issue here, but there is no other way to contact you (email doesnt seem to work)

**Comment by chriskapp** [comment]
Hi, no problem, so the handling of the required properties was missing in the API documentation viewer. I have commited a fix if you like you can get the latest version from the repo:
https://github.com/k42b3/evid/tree/master/build

**Comment by ghost** [comment]
Oh no, i think you dont understand what im trying to do here..

I'm trying to change the front end to have a Required field  

```
    html += '    <th>Property</th>';
    html += '    <th>Type</th>';
    html += '    <th>Required</th>';
    html += '    <th>Description</th>';
    html += '    <th>Constraints</th>';
```

And then use annoatations in the entity to do something like @required("true")  which will then be showed in the front end template.

The default value for required should be true (most parameters are going to be required obviously)

This would be pretty useful if you have something like a get route to a resource where you can have optimal parameters.

Can you tell me what i need to change in your framework to do this?

(Perhaps you could create a @Additional("key", "value") annotation that your framework could parse and then expose via the tool/doc in the api  under a additional key?

Thanks!

**Comment by chriskapp** [comment]
Ok, so in the entity you can already use a @Required annotation i.e.
https://github.com/apioo/psx-sample/blob/master/src/Sample/Model/Population.php#L22

This informations is also available in the front end template. There we have the
complete JsonSchema of the entity. So basically you only have to change
the frontend code to render the required column how you like.

With the last patch I have added a class so that required properties are 
rendered underlined but you can also easily add a new column where the required
property is listed:
https://github.com/k42b3/evid/blob/master/app/components/schema.js#L191

The @Required annotation works only for request and response payloads. If you want to
set a GET parameter as required you need to use i.e. the `@QueryParam(name="startIndex", type="integer", required=true)` annotation in the controller.

In general the annotations are there to convert a class to a JsonSchema. Iam not sure 
whether it is a good idea to have an annotation which accepts arbitrary key/values. We 
could add other annotations but they should be related to the JsonSchema spec. The 
available annotations are listed here:
https://github.com/apioo/psx-schema/tree/master/src/Parser/Popo/Annotation

I hope I understood you correct and this answers your question ;)

**Comment by ghost** [comment]
This looks amazing so far and thank you for the explanation!

I seem to encounter an issue when i try to build evid (https://github.com/k42b3/evid)

I pull it down via git clone and npm install all dependencies, but when i use $ grunt it does compile the files, (with no error message) but the files seem to be broken and dont work.

I also noticed that the generated files are WAY smaller than the original ones (when you first pull down the repo evid.min.css is 150 kb and evid.min.js is 861 kb) but when i hit $ grunt evid.min.css is 1kb and evid.min.js is only 14 kb so something has to be wrong..

What am i doing wrong?

If im bugging you too much please let me know, however if you have some kind of IM we could chat in for a little I'd appreciate it (so i dont clutter your project issues)

**Comment by chriskapp** [comment]
Ok this looks like the bower dependencies are missing. Do you have executed the `bower install` command after `npm install`? Then in your app/ folder should be a `bower_components` folder. The folder contains all js dependencies like angularjs etc.

> If im bugging you too much please let me know, however if you have some kind of IM we could chat in for a little I'd appreciate it (so i dont clutter your project issues)

This is no problem, this may help also other people which have similar issues. For other topics you can simply use my mail: https://github.com/apioo/psx-framework/blob/master/src/Base.php#L6
